выполнил ДЗ№2
htmlacademy-adaptive/2108721-cat-energy-27 pull request #2
Opened 2022-11-27 13:33 UTC by Grikus

Сверстаны 3 страницы мобильной версии. Не совсем понял что делать с макетом Меню.

2022-11-27 17:25 UTC, Kartaviy-arteom requested changes
svg преимуществ экспортировать нужно без фона

2022-11-27 17:25 UTC, Kartaviy-arteom commented on source/index.html
> +      <img src="../image/logo-text.svg" width="102" height="18" alt="Надпись CAT ENERGY.">
для картинки с текстом в alt лучше указать текст: "CAT ENERGY"

2022-11-27 17:25 UTC, Kartaviy-arteom commented on source/index.html
> +          <li class="site-list__item site-list__item--current">
тут ошибка в бэм-е

2022-11-27 17:25 UTC, Kartaviy-arteom commented on source/index.html
> +      <div class="programs_container">
тут ошибка в бэм-е

2022-11-27 17:25 UTC, Kartaviy-arteom commented on source/index.html
> +        </button>
тут ошибка в бэм-е

2022-11-27 17:25 UTC, Kartaviy-arteom commented on source/index.html
> +      </div>
тут ошибка в бэм-е

2022-11-27 17:25 UTC, Kartaviy-arteom commented on source/index.html
> +              <svg class="socail__link-image" width="27" height="17" viewBox="0 0 27 17" fill="none"
тут ошибка в бэм-е

2022-11-27 17:25 UTC, Kartaviy-arteom commented on source/index.html
> +    <a class="logo" href="index.html">
тут нет смысла делать ссылку саму на себя

2022-11-27 17:25 UTC, Kartaviy-arteom commented on source/index.html
> +      </button>
это кнопка внутри nav только все усложнит

2022-11-27 17:25 UTC, Kartaviy-arteom commented on source/index.html
> +            <a class="site-list__link" href="index.html">Главная</a>
убрать href на главной

2022-11-27 17:25 UTC, Kartaviy-arteom commented on source/index.html
> +      <div class="main-nav__container">
пока не понял зачем этот div вообще нужен

2022-11-27 17:25 UTC, Kartaviy-arteom commented on source/index.html
> +        <header class="about__header">
header тут не нужен

2022-11-27 17:25 UTC, Kartaviy-arteom commented on source/index.html
> +        <button class="about__button button" type="button">подобрать программу</button>
ссылка на страницу подбора

2022-11-27 17:25 UTC, Kartaviy-arteom commented on source/index.html
> +          <dt class="example__number">5 КГ</dt>
поменять текст местами в dd и dt

2022-11-27 17:25 UTC, Kartaviy-arteom commented on source/index.html
> +        </button>
в кнопку не нужна вкладывать две картинки. У тебя есть обертка, внутри две картинки и кнопка

2022-11-27 17:25 UTC, Kartaviy-arteom commented on source/index.html
> +          <img class="logo__image" src="../image/footer-logo.svg" width="128" height="24" alt="Надпись CAT ENERGY.">
просто в альте оставь "CAT ENERGY."

2022-11-27 17:25 UTC, Kartaviy-arteom commented on source/index.html
> +  <footer class="main-footer">
весь футер у тебя состоит из 2-х крупных блоков: "приглашение к сотрудничеству" и карта, нижняя часть с ссылками

2022-11-27 17:25 UTC, Kartaviy-arteom commented on source/form.html
> +  </header>
аналогично индексу, только будет ссылка на главную

2022-11-27 17:25 UTC, Kartaviy-arteom commented on source/form.html
> +        <input class="data-field__input name-input input" id="name" type="text" name="data" placeholder="БАРСИК"
data-field__input input input--text

2022-11-27 17:25 UTC, Kartaviy-arteom commented on source/form.html
> +      <p class="program__tooltip">* — Обязательные поля</p>
лучше не параграф

2022-11-27 17:25 UTC, Kartaviy-arteom commented on source/catalog.html
> +            <!-- псевдо с картинкой товара -->
фото товара - контентное изображение

2022-11-27 18:23 UTC, Grikus commented on source/index.html
> +      <img src="../image/logo-text.svg" width="102" height="18" alt="Надпись CAT ENERGY.">
исправил

2022-11-27 18:24 UTC, Grikus commented on source/index.html
> +          <li class="site-list__item site-list__item--current">
исправил на main-nav__item и main-nav__link

2022-11-27 18:25 UTC, Grikus commented on source/index.html
> +      <div class="programs_container">
добавил еще 1 _

2022-11-27 18:27 UTC, Grikus commented on source/index.html
> +        </button>
исправил

2022-11-27 18:31 UTC, Grikus commented on source/index.html
> +      </div>
исправил

2022-11-27 18:35 UTC, Grikus commented on source/index.html
> +  <footer class="main-footer">
перенес лого в блок с контактами

2022-11-27 18:37 UTC, Grikus commented on source/index.html
> +              <svg class="socail__link-image" width="27" height="17" viewBox="0 0 27 17" fill="none"
задал svg class=social__image

2022-11-27 18:37 UTC, Grikus commented on source/index.html
> +    <a class="logo" href="index.html">
исправил

2022-11-27 18:39 UTC, Grikus commented on source/index.html
> +            <a class="site-list__link" href="index.html">Главная</a>
исправил

2022-11-27 18:42 UTC, Grikus commented on source/index.html
> +      </button>
исправил

2022-11-27 18:42 UTC, Grikus commented on source/index.html
> +      <div class="main-nav__container">
в гайде говорили что каждый контенер служит для позиционирования, и что потом все равно пригодятся. я сделал в каждом блоке отдельный контейнер для этого.

2022-11-27 18:43 UTC, Grikus commented on source/index.html
> +        <header class="about__header">
убрал

2022-11-27 18:44 UTC, Grikus commented on source/index.html
> +        <button class="about__button button" type="button">подобрать программу</button>
исправил

2022-11-27 18:46 UTC, Grikus commented on source/index.html
> +          <dt class="example__number">5 КГ</dt>
исправил

2022-11-27 18:48 UTC, Grikus commented on source/index.html
> +        </button>
исправил

2022-11-27 18:48 UTC, Grikus commented on source/index.html
> +          <img class="logo__image" src="../image/footer-logo.svg" width="128" height="24" alt="Надпись CAT ENERGY.">
исправил

2022-11-27 18:49 UTC, Grikus commented on source/form.html
> +  </header>
исправил

2022-11-27 18:51 UTC, Grikus commented on source/form.html
> +        <input class="data-field__input name-input input" id="name" type="text" name="data" placeholder="БАРСИК"
исправил

2022-11-27 18:51 UTC, Grikus commented on source/form.html
> +      <p class="program__tooltip">* — Обязательные поля</p>
сделал span

2022-11-27 19:10 UTC, Grikus commented on source/catalog.html
> +            <!-- псевдо с картинкой товара -->
исправил

2022-11-28 16:41 UTC, Kartaviy-arteom approved these changes

2022-11-28 16:41 UTC, Kartaviy-arteom commented on source/index.html
> +      <div class="main-nav__container">
можно nav для этого использовать

2022-11-28 16:41 UTC, merged