Module3 task1
htmlacademy-adaptive/2108721-cat-energy-27 pull request #5
Opened 2022-12-01 18:06 UTC by Grikus

посмотри главное миксины перменные и тд. ну так и так в общем глянь правильно ли подход в стилизации

2022-12-03 21:48 UTC, Grikus commented
1. С котами в слайдере нужна помощь буквальная, шаг за шагом, не получается  у меня
2. В каталоге как разместить картинку с товаром по центру? у меня там гриды
3. в форме, блок комментарий, как сделать чтоб текст писался не по центру а сверху

2022-12-06 11:30 UTC, Kartaviy-arteom reviewed
tel-title, weight-title - может тебе нужен блок title

2022-12-06 11:30 UTC, Kartaviy-arteom commented on source/sass/style.scss
> +}
это тут не нужно

2022-12-06 11:30 UTC, Kartaviy-arteom commented on source/index.html
> +          <li>
тут в беме проблема socail__image

2022-12-06 11:30 UTC, Kartaviy-arteom commented on source/sass/blocks/visaully-hidden.scss
> +}
этому не место в блоках

2022-12-06 11:38 UTC, Kartaviy-arteom requested changes

2022-12-06 11:38 UTC, Kartaviy-arteom commented on source/sass/blocks/supplies.scss
> +  height: 289px;
не нужно тут ограничивать высоту

2022-12-06 14:48 UTC, romantsarew commented on source/sass/style.scss
> +}
убрал

2022-12-06 14:49 UTC, romantsarew commented on source/index.html
> +          <li>
исправил

2022-12-06 14:49 UTC, Grikus commented on source/sass/blocks/visaully-hidden.scss
> +}
перенес в миксины

2022-12-06 14:49 UTC, Grikus commented on source/sass/blocks/supplies.scss
> +  height: 289px;
исправил на 100%

2022-12-06 20:00 UTC, merged