Module4 task1
htmlacademy-adaptive/2108721-cat-energy-27 pull request #6
Opened 2022-12-07 19:58 UTC by Grikus

ДЗ №4

2022-12-10 15:23 UTC, Kartaviy-arteom requested changes
source/img/index/example-rectangle-medium.svg - это не нужно, тем более в нескольких размерах. Других свг тоже касается, это же свг
Нужно исправить контейнер, от него подправятся все остальные адаптивы

2022-12-10 15:23 UTC, Kartaviy-arteom commented on source/sass/blocks/container.scss
>    .container {
у тебя элемент больше вьюпорта, у тебя скролл горизонтальный появится
на мобильных тоже не нужно фиксировать ширину

2022-12-10 15:23 UTC, Kartaviy-arteom commented on source/sass/blocks/container.scss
>    .container {
на десктопе, если ты ограничиваешь контент максимальной шириной, выравнивается по центру

2022-12-11 18:25 UTC, Kartaviy-arteom requested changes

2022-12-11 18:25 UTC, Kartaviy-arteom commented on source/sass/blocks/about.scss
этот блок держится только из-за about-description. Если туда контентом придет пустая строка или его не будет, все развалится такого быть не должно

2022-12-11 18:25 UTC, Kartaviy-arteom commented on source/index.html
>          <a class="programs__choose button" href="form.html">подобрать программу</a>
это относится к секции выше

2022-12-11 18:25 UTC, Kartaviy-arteom commented on source/sass/blocks/about.scss
>    margin-bottom: 138px;
здесь нужно использовать внутренний отступ

2022-12-11 18:25 UTC, Kartaviy-arteom commented on source/sass/blocks/about.scss
> +      background-color: rgba($color: #68b738, $alpha: 85%);
rgba(#68b738, 85%);

2022-12-11 18:25 UTC, Kartaviy-arteom commented on source/sass/blocks/programs.scss
> +.programs__link-container {
зачем эта обертка? из нее выпадает ссылка

2022-12-11 18:25 UTC, Kartaviy-arteom commented on source/sass/blocks/contacts.scss
>  .contacts__map {
не выдержи переполнения при изменении кол-ва текста сверху

2022-12-11 18:25 UTC, Kartaviy-arteom commented on source/sass/blocks/products.scss
> +.products__item-parametrs {
переполнение в параметрах

2022-12-11 18:25 UTC, Kartaviy-arteom commented on source/sass/blocks/container.scss
> +    padding: 0 110px;
посмотри как у тебе ведет сайт на ширине 1200px, например в каталоге

2022-12-11 18:25 UTC, Kartaviy-arteom commented on source/sass/blocks/comment-field.scss
> +    padding: 33px 1038px 36px 0;
этот правый падддинг ломает интерфейс

2022-12-11 18:25 UTC, Kartaviy-arteom commented on source/sass/blocks/contacts.scss
> +    z-index: 5;
белый фон должен быть поверх карты, это не работает потому что карты внутри этого контейнера

2022-12-12 09:08 UTC, Grikus commented on source/index.html
>          <a class="programs__choose button" href="form.html">подобрать программу</a>
перенес

2022-12-12 09:09 UTC, Grikus commented on source/sass/blocks/about.scss
>    margin-bottom: 138px;
исправил

2022-12-12 09:09 UTC, Grikus commented on source/sass/blocks/about.scss
> +      background-color: rgba($color: #68b738, $alpha: 85%);
исправил

2022-12-12 09:21 UTC, Grikus commented on source/sass/blocks/programs.scss
> +.programs__link-container {
убрал

2022-12-12 10:16 UTC, Grikus commented on source/sass/blocks/contacts.scss
>  .contacts__map {
перенес карту в другой див

2022-12-12 10:20 UTC, Grikus commented on source/sass/blocks/products.scss
> +.products__item-parametrs {
все в порядке

2022-12-12 10:21 UTC, Grikus commented on source/sass/blocks/contacts.scss
> +    z-index: 5;
исправил

2022-12-12 10:28 UTC, romantsarew commented on source/sass/blocks/about.scss
исправил

2022-12-12 12:01 UTC, Grikus commented on source/sass/blocks/container.scss
> +    padding: 0 110px;
поменял брейкпоинт на 1440

2022-12-12 12:01 UTC, Grikus commented on source/sass/blocks/comment-field.scss
> +    padding: 33px 1038px 36px 0;
теперь все нормально

2022-12-13 20:10 UTC, merged