Module5 task1
htmlacademy-adaptive/2108721-cat-energy-27 pull request #7
Opened 2022-12-15 10:42 UTC by Grikus

ДЗ№5 с учетом предыдущих поправок

2022-12-18 10:07 UTC, Kartaviy-arteom requested changes
пиксель пефект страниц нужно править
Фон главной на планшете, нет банки
advantages__list - это ol
Карточки каталога, как в макете

2022-12-18 10:07 UTC, Kartaviy-arteom commented on source/sass/blocks/footer.scss
> +
реализовать карту в соответствии с https://up.htmlacademy.ru/adaptive/27/project/cat-energy#cat-energy-4-5

2022-12-18 10:07 UTC, Kartaviy-arteom commented on source/sass/blocks/example.scss
> +    background: linear-gradient(to bottom, #ffffff 48%, #f2f2f2 48%);
слайдер сделать как в макете
Внешний вид этого блока на планшете

2022-12-18 10:07 UTC, Kartaviy-arteom commented on source/sass/blocks/about.scss
> +  font-weight: 400;
главный экран на десктопе в соответствии с пунктом https://up.htmlacademy.ru/adaptive/27/project/cat-energy#cat-energy-4-11

2022-12-18 10:07 UTC, Kartaviy-arteom commented on source/sass/blocks/nav.scss
> +  position: relative;
меню с отключенным js не работает

2022-12-18 10:07 UTC, Kartaviy-arteom commented on source/sass/blocks/comment-field.scss
> +  @include field-title;
эти блоки не выдерживают изменения текста

2022-12-18 10:07 UTC, Kartaviy-arteom commented on source/form.html
> +          <legend class="comment-field__title">Комментарий</legend>
тут нужен не input, а textarea

2022-12-19 10:02 UTC, romantsarew commented on source/sass/blocks/about.scss
> +  font-weight: 400;
сделал

2022-12-19 10:19 UTC, Grikus commented on source/form.html
> +          <legend class="comment-field__title">Комментарий</legend>
исправил

2022-12-19 10:46 UTC, Grikus commented on source/sass/blocks/footer.scss
> +
исправил, банка добавлена, список переделал, карточки как в макете

2022-12-19 10:47 UTC, Grikus commented on source/sass/blocks/nav.scss
> +  position: relative;
сделал

2022-12-19 10:47 UTC, Grikus commented on source/sass/blocks/comment-field.scss
> +  @include field-title;
исправлено

2022-12-21 12:52 UTC, merged